// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Basic.demo': typeof import('./demos/zhCN/basic/basic.demo.md')['default']
    BasicDemo: typeof import('./demos/zhCN/basic/BasicDemo.vue')['default']
    C: typeof import('./demos/zhCN/basic/c.vue')['default']
    CustomParams: typeof import('./demos/zhCN/custom-params/index.md')['default']
    'CustomParams.demo': typeof import('./demos/zhCN/custom-params/custom-params.demo.md')['default']
    CustomParamsDemo: typeof import('./demos/zhCN/custom-params/CustomParamsDemo.vue')['default']
    DemoHeader: typeof import('./components/DemoHeader.vue')['default']
    DemoWrap: typeof import('./components/DemoWrap.vue')['default']
    DocsFooter: typeof import('./components/DocsFooter.vue')['default']
    DocsHeader: typeof import('./components/DocsHeader.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderMenus: typeof import('./components/SiderMenus.vue')['default']
    Started: typeof import('./demos/zhCN/started/index.md')['default']
  }
}
