// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Basic.demo': typeof import('./demos/zhCN/basic/basic.demo.md')['default']
    BasicDemo: typeof import('./demos/zhCN/basic/BasicDemo.vue')['default']
    'Complex.demo': typeof import('./demos/zhCN/complex/complex.demo.md')['default']
    ComplexDemo: typeof import('./demos/zhCN/complex/ComplexDemo.vue')['default']
    'CustomParams.demo': typeof import('./demos/zhCN/custom-params/custom-params.demo.md')['default']
    CustomParamsDemo: typeof import('./demos/zhCN/custom-params/CustomParamsDemo.vue')['default']
    DemoWrap: typeof import('./components/DemoWrap.vue')['default']
    DocsFooter: typeof import('./components/DocsFooter.vue')['default']
    DocsHeader: typeof import('./components/DocsHeader.vue')['default']
    'Filter.demo': typeof import('./demos/zhCN/filter/filter.demo.md')['default']
    FilterDemo: typeof import('./demos/zhCN/filter/FilterDemo.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
    'Pagination.demo': typeof import('./demos/zhCN/pagination/pagination.demo.md')['default']
    PaginationDemo: typeof import('./demos/zhCN/pagination/PaginationDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderMenus: typeof import('./components/SiderMenus.vue')['default']
  }
}
