on:
  release:
    types: [published]
jobs:
  send-msg:
    runs-on: ubuntu-latest
    steps:
    - name: post message
      uses: foxundermoon/feishu-action@v2
      with:
        url: https://open.feishu.cn/open-apis/bot/v2/hook/${{ secrets.FEISHU_NOTIYFY_TOKEN }}
        msg_type: post
        content: |
          post:
            zh_cn:
              title: ${{github.event.payload.release.name}}
              content:
              - - tag: a
                  text: '详情信息'
                  href: ${{github.event.payload.release.html_url}}