on:
  release:
    types: [published]
jobs:
  send-msg:
    runs-on: ubuntu-latest
    steps:
    - name: post message
      uses: foxundermoon/feishu-action@v2
      with:
        url: https://open.feishu.cn/open-apis/bot/v2/hook/${{ secrets.FEISHU_NOTIYFY_TOKEN }}
        msg_type: post
        content: |
          post:
            zh_cn:
              title: "版本发布通知: ${{ github.event.release.name }}"
              content:
              - - tag: text
                  text: 'version'
                  href: ${{ github.event.release.tag_name }}
              - - tag: lark_md
                  text: "${{ github.event.release.body }}"
              - - tag: a
                  text: '详情信息'
                  href: ${{ github.event.release.html_url }}