on:
  release:
    types: [published]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: sen-feishu-msg
      uses: wei/curl@v1
      with:
        args: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"msg_type":"text","content":{"text":"版本发布通知 \n title:${{ github.event.payload.release.name }}\n version:${{ github.event.payload.release.tag_name }}"}}' \
          https://open.feishu.cn/open-apis/bot/v2/hook/${{ secrets.FEISHU_NOTIYFY_TOKEN }}
